name: leafdapp_user
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  web3dart: ^2.7.3
  flutter_riverpod: ^2.5.1
  uuid: ^4.4.0
  http: ^1.2.1
  web_socket_channel: ^2.4.5
  mobile_scanner: ^4.0.1
  flutter_secure_storage: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - src/contracts/Leaf.json
